name: GoCardless
description: GoCardless is the UK's #1 for Direct Debit, serving more companies than any other provider. Perfect for recurring billing and B2B invoicing.
url: https://gocardless.com
baseurl: /
email: help@gocardless.com
twitter: gocardless
phone: '020 7183 8674'

highlighter: false
lsi: false
future: false
plugins: ./_plugins
permalink: /:title/
exclude: ['_assets', 'README.md', 'Gemfile.lock', 'Gemfile', 'Capfile', 'config', 'vendor']
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables', 'strikethrough']
excerpt_length: 250

assets:
  baseurl: /assets
  sources:
    - _assets
    - _assets/images
    - _assets/css
  compress:
    js:   uglifier
    css:  sass
